<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.14" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechTaskReview.Application\TechTaskReview.Application.csproj" />
    <ProjectReference Include="..\TechTaskReview.Domain\TechTaskReview.Domain.csproj" />
    <ProjectReference Include="..\TechTaskReview.Infrastructure\TechTaskReview.Infrastructure.csproj" />
  </ItemGroup>

</Project>
